import Head from "next/head";
import Contact from "../components/Contact";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" mx-3 lg:mx-80 text-center lg:text-left">
        <Contact />
      </main>
    </div>
  );
}
